<?php

declare(strict_types=1);

namespace App\Services;

use App\Models\AiSettingsRepository;

/**
 * AI content assistant. When an LLM provider is configured in admin it calls
 * that API; otherwise it produces strong template-based copy so the tool is
 * always useful. Output is a list of ready-to-use variations for the chosen
 * content type.
 */
final class ContentAssistantService
{
    /** @var array<string, string> */
    public const TYPES = [
        'meta_description' => 'Meta descriptions (SEO)',
        'title_tag' => 'SEO title tags',
        'blog_outline' => 'Blog post outline',
        'faq' => 'FAQ questions & answers',
        'product_description' => 'Product / service description',
        'social_post' => 'Social media posts',
        'email_subject' => 'Email subject lines',
        'cta' => 'Call-to-action buttons',
    ];

    /** @var array<int, string> */
    public const TONES = ['Professional', 'Friendly', 'Confident', 'Playful', 'Urgent'];

    private AiSettingsRepository $settings;

    public function __construct(?AiSettingsRepository $settings = null)
    {
        $this->settings = $settings ?? new AiSettingsRepository();
    }

    /**
     * @param array{tone?: string, audience?: string, keyword?: string} $opts
     * @return array{type: string, label: string, source: string, items: array<int, string>, note: string}
     */
    public function generate(string $type, string $topic, array $opts = []): array
    {
        $type = array_key_exists($type, self::TYPES) ? $type : 'meta_description';
        $topic = trim($topic);
        $tone = in_array($opts['tone'] ?? '', self::TONES, true) ? (string) $opts['tone'] : 'Professional';
        $audience = trim((string) ($opts['audience'] ?? ''));
        $keyword = trim((string) ($opts['keyword'] ?? '')) ?: $topic;

        $items = [];
        $source = 'template';
        $note = 'Generated from proven copy templates. Edit to fit your brand voice.';

        if ($this->settings->isLive()) {
            $ai = $this->callProvider($type, $topic, $tone, $audience, $keyword);
            if ($ai !== null && $ai !== []) {
                $items = $ai;
                $source = 'ai';
                $note = 'Generated by your configured AI provider. Always review before publishing.';
            }
        }

        if ($items === []) {
            $items = $this->template($type, $topic, $tone, $audience, $keyword);
        }

        return [
            'type' => $type,
            'label' => self::TYPES[$type],
            'source' => $source,
            'items' => array_values(array_filter(array_map('trim', $items), static fn ($s) => $s !== '')),
            'note' => $note,
        ];
    }

    // ------------------------------------------------------------------
    // Live LLM providers
    // ------------------------------------------------------------------

    /**
     * @return array<int, string>|null
     */
    private function callProvider(string $type, string $topic, string $tone, string $audience, string $keyword): ?array
    {
        $s = $this->settings->current();
        $provider = (string) ($s['provider'] ?? 'openai');
        $apiKey = (string) ($s['api_key'] ?? '');
        $model = (string) ($s['model'] ?? '');
        $prompt = $this->prompt($type, $topic, $tone, $audience, $keyword);

        try {
            $text = $provider === 'anthropic'
                ? $this->callAnthropic($apiKey, $model, $prompt)
                : $this->callOpenAi($apiKey, $model, $prompt);
        } catch (\Throwable $exception) {
            (new AuditLogger())->log('ai.content.provider_failed', ['provider' => $provider, 'error' => $exception->getMessage()]);
            return null;
        }

        if (!is_string($text) || trim($text) === '') {
            return null;
        }

        return $this->splitLines($text);
    }

    private function prompt(string $type, string $topic, string $tone, string $audience, string $keyword): string
    {
        $forWhom = $audience !== '' ? " Target audience: {$audience}." : '';
        $instructions = [
            'meta_description' => "Write 3 SEO meta descriptions (each 150-158 characters) for \"{$topic}\", naturally including the keyword \"{$keyword}\". End each with a light call to action.",
            'title_tag' => "Write 5 SEO title tags (each under 60 characters) for \"{$topic}\", front-loading the keyword \"{$keyword}\".",
            'blog_outline' => "Write a blog post outline for \"{$topic}\" targeting the keyword \"{$keyword}\": a working title, then 6-8 H2 section headings, each with one short line on what to cover.",
            'faq' => "Write 5 FAQ questions and concise answers (2-3 sentences each) about \"{$topic}\" for the keyword \"{$keyword}\".",
            'product_description' => "Write a persuasive product/service description for \"{$topic}\": one opening paragraph, then 5 benefit bullet points, then a closing call to action.",
            'social_post' => "Write 3 social media posts promoting \"{$topic}\" (one LinkedIn, one Facebook, one X/Twitter), each with a hook and 2-3 relevant hashtags.",
            'email_subject' => "Write 6 email subject lines for a campaign about \"{$topic}\", mixing curiosity, benefit and urgency. Keep them under 55 characters.",
            'cta' => "Write 6 short call-to-action button labels (2-5 words each) for \"{$topic}\".",
        ];
        $task = $instructions[$type] ?? $instructions['meta_description'];

        return "You are an expert SEO copywriter for a web design and digital marketing agency. Tone: {$tone}.{$forWhom}\n\n{$task}\n\nReturn each item on its own line with no numbering, quotes or extra commentary.";
    }

    private function callOpenAi(string $apiKey, string $model, string $prompt): ?string
    {
        $payload = json_encode([
            'model' => $model !== '' ? $model : 'gpt-4o-mini',
            'messages' => [['role' => 'user', 'content' => $prompt]],
            'temperature' => 0.8,
            'max_tokens' => 700,
        ], JSON_UNESCAPED_SLASHES);

        $response = $this->httpPost('https://api.openai.com/v1/chat/completions', $payload, [
            'Authorization: Bearer ' . $apiKey,
            'Content-Type: application/json',
        ]);
        $data = is_string($response) ? json_decode($response, true) : null;

        return is_array($data) ? ($data['choices'][0]['message']['content'] ?? null) : null;
    }

    private function callAnthropic(string $apiKey, string $model, string $prompt): ?string
    {
        $payload = json_encode([
            'model' => $model !== '' ? $model : 'claude-haiku-4-5-20251001',
            'max_tokens' => 700,
            'messages' => [['role' => 'user', 'content' => $prompt]],
        ], JSON_UNESCAPED_SLASHES);

        $response = $this->httpPost('https://api.anthropic.com/v1/messages', $payload, [
            'x-api-key: ' . $apiKey,
            'anthropic-version: 2023-06-01',
            'Content-Type: application/json',
        ]);
        $data = is_string($response) ? json_decode($response, true) : null;

        return is_array($data) ? ($data['content'][0]['text'] ?? null) : null;
    }

    private function httpPost(string $url, string $body, array $headers): ?string
    {
        $context = stream_context_create([
            'http' => [
                'method' => 'POST',
                'header' => implode("\r\n", $headers),
                'content' => $body,
                'ignore_errors' => true,
                'timeout' => 25,
            ],
        ]);
        $response = @file_get_contents($url, false, $context);

        return is_string($response) ? $response : null;
    }

    /**
     * @return array<int, string>
     */
    private function splitLines(string $text): array
    {
        $lines = preg_split('/\r?\n/', trim($text)) ?: [];
        $clean = [];
        foreach ($lines as $line) {
            // Strip list markers, numbering and stray quotes.
            $line = preg_replace('/^\s*(?:\d+[\.\)]|[-*•])\s*/u', '', (string) $line);
            $line = trim((string) $line, " \t\"'");
            if ($line !== '') {
                $clean[] = $line;
            }
        }

        return $clean;
    }

    // ------------------------------------------------------------------
    // Template fallback (no API key required)
    // ------------------------------------------------------------------

    /**
     * @return array<int, string>
     */
    private function template(string $type, string $topic, string $tone, string $audience, string $keyword): array
    {
        $t = $topic !== '' ? $topic : 'your business';
        $kw = $keyword !== '' ? $keyword : $t;
        $who = $audience !== '' ? $audience : 'customers';
        $Kw = $this->titleCase($kw);
        $Topic = $this->titleCase($t);

        switch ($type) {
            case 'title_tag':
                return [
                    "{$Kw} | Trusted Experts You Can Rely On",
                    "{$Kw} That Delivers Real Results in 2026",
                    "Affordable {$Kw} for Growing Businesses",
                    "{$Kw}: Get a Free Quote Today",
                    "The Smarter Way to Handle {$Kw}",
                ];

            case 'blog_outline':
                return [
                    "Working title: The Complete Guide to {$Topic} in 2026",
                    "H2: What is {$Kw} and why it matters for {$who}",
                    "H2: The real cost of getting {$Kw} wrong",
                    "H2: Step-by-step: how {$Kw} actually works",
                    "H2: 5 mistakes to avoid with {$Kw}",
                    "H2: How to choose the right partner for {$Kw}",
                    "H2: Checklist — is your {$Topic} ready?",
                    "H2: FAQ and next steps",
                ];

            case 'faq':
                return [
                    "Q: How much does {$kw} cost? A: It depends on scope, but we price {$kw} transparently with a fixed quote up front — no surprises. Most {$who} start with a free consultation so you know the number before committing.",
                    "Q: How long does {$kw} take? A: A typical {$kw} project runs a few weeks from kickoff to launch. We give you a clear timeline on day one and keep you updated at every milestone.",
                    "Q: Do I need technical knowledge for {$kw}? A: Not at all. We handle the technical side and explain everything in plain language, so {$who} stay in control without the jargon.",
                    "Q: What makes your {$kw} different? A: We combine {$kw} with measurable results — you get work that looks great and actually moves the numbers that matter to your business.",
                    "Q: What happens after the {$kw} project ends? A: You're never left stranded. We offer ongoing support and care plans so your {$topic} keeps performing long after launch.",
                ];

            case 'product_description':
                return [
                    "Meet {$Topic} — built for {$who} who want results without the guesswork. Every detail is designed to save you time, win you trust and turn visitors into paying customers.",
                    "• Fast, reliable and built to the highest modern standards",
                    "• Designed around your goals, not a generic template",
                    "• Optimised for search, speed and conversions from day one",
                    "• Backed by real support from a team that answers",
                    "• Transparent pricing with no hidden costs",
                    "Ready to get started? Request your free {$kw} quote today and see the difference.",
                ];

            case 'social_post':
                return [
                    "LinkedIn: Struggling with {$kw}? You're not alone. Here's how the right approach to {$topic} helps {$who} save time and win more business. 👇 #{$this->hashtag($kw)} #{$this->hashtag('business')} #DigitalGrowth",
                    "Facebook: 🚀 Big news for {$who}! Our {$kw} service is helping local businesses grow faster than ever. Book a free consultation and let's talk about your {$topic}. #{$this->hashtag($kw)} #SmallBusiness",
                    "X/Twitter: {$Topic} done right = more customers, less stress. That's what we do. DM us for a free {$kw} audit. #{$this->hashtag($kw)} #SEO #WebDesign",
                ];

            case 'email_subject':
                return [
                    "Your {$kw} could be costing you customers",
                    "A quick win for your {$topic}",
                    "{$Kw}, made simple (finally)",
                    "Still putting off {$kw}?",
                    "Free {$kw} audit — only a few spots left",
                    "The {$kw} mistake most {$who} make",
                ];

            case 'cta':
                return [
                    "Get My Free Quote",
                    "Start My {$Kw} Project",
                    "Book a Free Call",
                    "See How It Works",
                    "Claim My Free Audit",
                    "Talk to an Expert",
                ];

            case 'meta_description':
            default:
                return [
                    $this->clip("Looking for {$kw}? We help {$who} get more from their {$topic} with proven, results-driven work. Get your free quote today.", 158),
                    $this->clip("{$Kw} that actually works. Trusted by {$who} across Ireland for fast, reliable, affordable {$topic}. See what we can do for you.", 158),
                    $this->clip("Turn your {$topic} into a growth engine. Expert {$kw}, transparent pricing and real support. Book your free consultation now.", 158),
                ];
        }
    }

    private function titleCase(string $value): string
    {
        return ucwords(strtolower(trim($value)));
    }

    private function hashtag(string $value): string
    {
        $parts = preg_split('/[^a-z0-9]+/i', $value) ?: [];
        $tag = '';
        foreach ($parts as $part) {
            $tag .= ucfirst(strtolower($part));
        }

        return $tag !== '' ? $tag : 'Business';
    }

    private function clip(string $value, int $max): string
    {
        $value = trim(preg_replace('/\s+/', ' ', $value) ?? '');
        if (mb_strlen($value) <= $max) {
            return $value;
        }

        return rtrim(mb_substr($value, 0, $max - 1)) . '…';
    }
}
