<?php

declare(strict_types=1);

use App\Controllers\AdminController;
use App\Controllers\AdminCmsController;
use App\Controllers\AccountController;
use App\Controllers\BlogController;
use App\Controllers\CheckoutController;
use App\Controllers\ForumController;
use App\Controllers\HomeController;
use App\Controllers\InstallController;
use App\Controllers\PageController;
use App\Controllers\PaymentWebhookController;
use App\Controllers\ShopController;
use App\Controllers\SupportController;
use App\Controllers\ToolsController;

$router->get('/install', [InstallController::class, 'index']);
$router->post('/install', [InstallController::class, 'store']);
$router->get('/', [HomeController::class, 'index']);
$router->get('/about', [PageController::class, 'about']);
$router->get('/services', [PageController::class, 'services']);
$router->get('/services/{slug}', [PageController::class, 'service']);
$router->get('/portfolio', [PageController::class, 'portfolio']);
$router->get('/code-shop', [ShopController::class, 'index']);
$router->get('/code-shop/{slug}', [ShopController::class, 'show']);
$router->post('/code-shop/{slug}/checkout', [CheckoutController::class, 'start']);
$router->get('/case-studies', [PageController::class, 'caseStudies']);
$router->get('/process', [PageController::class, 'process']);
$router->get('/technologies', [PageController::class, 'technologies']);
$router->get('/testimonials', [PageController::class, 'testimonials']);
$router->get('/pricing', [PageController::class, 'pricing']);
$router->get('/faq', [PageController::class, 'faq']);
$router->get('/contact', [PageController::class, 'contact']);
$router->post('/contact', [PageController::class, 'sendContact']);
$router->post('/chatbot/lead', [PageController::class, 'chatLead']);
$router->post('/webhooks/stripe', [PaymentWebhookController::class, 'stripe']);
$router->post('/webhooks/paypal', [PaymentWebhookController::class, 'paypal']);
$router->get('/account/forms', [AccountController::class, 'forms']);
$router->post('/account/login', [AccountController::class, 'login']);
$router->post('/account/register', [AccountController::class, 'register']);
$router->get('/tech-news-feed', [PageController::class, 'techNews']);
$router->get('/free-penetration-testing-tools', [ToolsController::class, 'index']);
$router->post('/free-penetration-testing-tools/headers', [ToolsController::class, 'analyzeHeaders']);
$router->post('/free-penetration-testing-tools/dns', [ToolsController::class, 'analyzeDns']);
$router->post('/free-penetration-testing-tools/tls', [ToolsController::class, 'analyzeTls']);
$router->post('/free-penetration-testing-tools/well-known', [ToolsController::class, 'analyzeWellKnown']);
$router->post('/tools/access/send-code', [ToolsController::class, 'sendAccessCode']);
$router->post('/tools/access/verify', [ToolsController::class, 'verifyAccessCode']);
$router->get('/tools', [ToolsController::class, 'hub']);
$router->get('/seo-tools', [ToolsController::class, 'seoTools']);
$router->post('/seo-tools/audit', [ToolsController::class, 'auditSeo']);
$router->get('/serp-checker', [ToolsController::class, 'serpChecker']);
$router->post('/serp-checker/check', [ToolsController::class, 'checkSerp']);
$router->get('/ai-website-growth-consultant', [ToolsController::class, 'growthConsultant']);
$router->get('/instant-website-quote-calculator', [ToolsController::class, 'quoteCalculator']);
$router->get('/security-score-badge-generator', [ToolsController::class, 'securityBadge']);
$router->get('/client-portal-preview', [ToolsController::class, 'clientPortalPreview']);
$router->get('/ppc-roi-calculator', [ToolsController::class, 'ppcRoiCalculator']);
$router->get('/before-after-speed-simulator', [ToolsController::class, 'speedSimulator']);
$router->get('/ai-automation-finder', [ToolsController::class, 'automationFinder']);
$router->get('/support', [SupportController::class, 'index']);
$router->post('/support/tickets', [SupportController::class, 'store']);
$router->get('/privacy-policy', [PageController::class, 'legal']);
$router->get('/cookie-policy', [PageController::class, 'legal']);
$router->get('/terms-and-conditions', [PageController::class, 'legal']);
$router->get('/search', [PageController::class, 'search']);
$router->get('/forum', [ForumController::class, 'index']);
$router->get('/forum/{slug}', [ForumController::class, 'show']);
$router->post('/forum/{slug}/posts', [ForumController::class, 'storePost']);
$router->get('/blog', [BlogController::class, 'index']);
$router->get('/blog/{slug}', [BlogController::class, 'show']);
$router->get('/admin', [AdminController::class, 'login']);
$router->post('/admin/login', [AdminController::class, 'authenticate']);
$router->get('/admin/dashboard', [AdminController::class, 'dashboard']);
$router->get('/admin/modules/{slug}', [AdminController::class, 'module']);
$router->post('/admin/modules/{slug}/actions', [AdminController::class, 'saveModuleDraft']);
$router->post('/admin/media/upload', [AdminController::class, 'uploadMedia']);
$router->post('/admin/forum-members/verify', [AdminController::class, 'verifyForumMember']);
$router->post('/admin/newsletter-offer', [AdminController::class, 'updateNewsletterOffer']);
$router->post('/admin/mail-settings', [AdminController::class, 'updateMailSettings']);
$router->post('/admin/mail-settings/test', [AdminController::class, 'testMailSettings']);
$router->post('/admin/paypal-settings', [AdminController::class, 'updatePayPalSettings']);
$router->get('/admin/cms/fonts', [AdminCmsController::class, 'fontOptions']);
$router->post('/admin/cms/add-missing-tables', [AdminCmsController::class, 'addMissingTables']);
$router->post('/admin/cms/theme-assets', [AdminCmsController::class, 'uploadThemeAsset']);
$router->post('/admin/cms/typography', [AdminCmsController::class, 'saveTypography']);
$router->post('/admin/cms/custom-code', [AdminCmsController::class, 'saveCustomCodeAsset']);
$router->post('/admin/cms/script-injections', [AdminCmsController::class, 'saveScriptInjection']);
$router->post('/admin/cms/products', [AdminCmsController::class, 'saveProduct']);
$router->post('/admin/cms/product-assets', [AdminCmsController::class, 'uploadProductAsset']);
$router->post('/admin/logout', [AdminController::class, 'logout']);
