<?php

declare(strict_types=1);

use App\Controllers\AdminController;
use App\Controllers\AdminCmsController;
use App\Controllers\AdminCommerceController;
use App\Controllers\AccountController;
use App\Controllers\BacklinksController;
use App\Controllers\BlogController;
use App\Controllers\CheckoutController;
use App\Controllers\CronController;
use App\Controllers\ForumController;
use App\Controllers\HomeController;
use App\Controllers\InstallController;
use App\Controllers\LocationController;
use App\Controllers\MembershipController;
use App\Controllers\OffersController;
use App\Controllers\PageController;
use App\Controllers\PaymentWebhookController;
use App\Controllers\SearchConsoleController;
use App\Controllers\ShopController;
use App\Controllers\SupportController;
use App\Controllers\ToolsController;

$router->get('/install', [InstallController::class, 'index']);
$router->post('/install', [InstallController::class, 'store']);
$router->get('/', [HomeController::class, 'index']);
$router->get('/about', [PageController::class, 'about']);
$router->get('/services', [PageController::class, 'services']);
$router->get('/services/{slug}', [PageController::class, 'service']);
$router->get('/portfolio', [PageController::class, 'portfolio']);
$router->get('/code-shop', [ShopController::class, 'index']);
$router->get('/code-shop/{slug}', [ShopController::class, 'show']);
$router->post('/code-shop/{slug}/checkout', [CheckoutController::class, 'start']);
$router->get('/case-studies', [PageController::class, 'caseStudies']);
$router->get('/case-studies/{slug}', [PageController::class, 'caseStudy']);
$router->get('/process', [PageController::class, 'process']);
$router->get('/technologies', [PageController::class, 'technologies']);
$router->get('/testimonials', [PageController::class, 'testimonials']);
$router->get('/pricing', [PageController::class, 'pricing']);
$router->get('/membership', [MembershipController::class, 'index']);
$router->post('/membership/join', [MembershipController::class, 'join']);
$router->get('/locations', [LocationController::class, 'hub']);
$router->get('/locations/{county}', [LocationController::class, 'county']);
$router->get('/backlinks', [BacklinksController::class, 'index']);
$router->post('/backlinks/order', [BacklinksController::class, 'order']);
$router->get('/website-care-plans', [OffersController::class, 'carePlans']);
$router->post('/website-care-plans/order', [OffersController::class, 'orderCarePlan']);
$router->get('/website-audit', [OffersController::class, 'audit']);
$router->post('/website-audit/order', [OffersController::class, 'orderAudit']);
$router->get('/speed-rescue', [OffersController::class, 'speedRescue']);
$router->post('/speed-rescue/order', [OffersController::class, 'orderSpeedRescue']);
$router->get('/badge.svg', [ToolsController::class, 'badgeSvg']);
$router->get('/faq', [PageController::class, 'faq']);
$router->get('/contact', [PageController::class, 'contact']);
$router->post('/contact', [PageController::class, 'sendContact']);
$router->post('/chatbot/lead', [PageController::class, 'chatLead']);
$router->post('/webhooks/stripe', [PaymentWebhookController::class, 'stripe']);
$router->post('/webhooks/paypal', [PaymentWebhookController::class, 'paypal']);
$router->get('/account/forms', [AccountController::class, 'forms']);
$router->post('/account/login', [AccountController::class, 'login']);
$router->post('/account/register', [AccountController::class, 'register']);
$router->get('/account/dashboard', [AccountController::class, 'dashboard']);
$router->post('/account/reports/save', [AccountController::class, 'saveReport']);
$router->post('/account/reports/delete', [AccountController::class, 'deleteReport']);
$router->post('/account/monitors/add', [AccountController::class, 'addMonitor']);
$router->post('/account/monitors/delete', [AccountController::class, 'deleteMonitor']);
$router->post('/account/site', [AccountController::class, 'saveSite']);
$router->post('/account/site/analyze', [AccountController::class, 'runSiteAnalysis']);
$router->post('/account/logout', [AccountController::class, 'logout']);
$router->get('/account/search-console', [SearchConsoleController::class, 'dashboard']);
$router->get('/account/search-console/connect', [SearchConsoleController::class, 'connect']);
$router->get('/account/search-console/callback', [SearchConsoleController::class, 'callback']);
$router->post('/account/search-console/site', [SearchConsoleController::class, 'selectSite']);
$router->post('/account/search-console/backlinks', [SearchConsoleController::class, 'importBacklinks']);
$router->post('/account/search-console/disconnect', [SearchConsoleController::class, 'disconnect']);
$router->get('/cron/run-monitors', [CronController::class, 'runMonitors']);
$router->get('/cron/run-abandoned-orders', [CronController::class, 'runAbandonedOrders']);
$router->get('/cron/run-rank-tracker', [CronController::class, 'runRankTracker']);
$router->get('/cron/run-site-metrics', [CronController::class, 'runSiteMetrics']);
$router->get('/tech-news-feed', [PageController::class, 'techNews']);
$router->get('/ethical-hacking-toolkit', [ToolsController::class, 'ethicalHackingToolkit']);
$router->post('/ethical-hacking-toolkit/exposure', [ToolsController::class, 'analyzeExposure']);
$router->get('/ethical-hacking-tools', [ToolsController::class, 'ethicalHackingTools']);
$router->get('/free-penetration-testing-tools', [ToolsController::class, 'index']);
$router->post('/free-penetration-testing-tools/headers', [ToolsController::class, 'analyzeHeaders']);
$router->post('/free-penetration-testing-tools/dns', [ToolsController::class, 'analyzeDns']);
$router->post('/free-penetration-testing-tools/tls', [ToolsController::class, 'analyzeTls']);
$router->post('/free-penetration-testing-tools/well-known', [ToolsController::class, 'analyzeWellKnown']);
$router->post('/tools/access/send-code', [ToolsController::class, 'sendAccessCode']);
$router->post('/tools/access/verify', [ToolsController::class, 'verifyAccessCode']);
$router->get('/tools', [ToolsController::class, 'hub']);
$router->get('/tools/security-headers', [ToolsController::class, 'securityHeaders']);
$router->get('/tools/dns-email', [ToolsController::class, 'dnsEmail']);
$router->get('/tools/tls-ssl', [ToolsController::class, 'tlsSsl']);
$router->get('/tools/security-txt', [ToolsController::class, 'securityTxt']);
$router->get('/tools/tech-stack', [ToolsController::class, 'techStack']);
$router->post('/tools/tech-stack', [ToolsController::class, 'analyzeTechStack']);
$router->get('/tools/pagespeed', [ToolsController::class, 'pagespeed']);
$router->post('/tools/pagespeed', [ToolsController::class, 'analyzePagespeed']);
$router->get('/tools-pricing', [ToolsController::class, 'toolsPricing']);
$router->get('/seo-tools', [ToolsController::class, 'seoTools']);
$router->post('/seo-tools/audit', [ToolsController::class, 'auditSeo']);
$router->get('/site-crawler', [ToolsController::class, 'siteCrawler']);
$router->post('/site-crawler/run', [ToolsController::class, 'runSiteCrawl']);
$router->get('/serp-checker', [ToolsController::class, 'serpChecker']);
$router->post('/serp-checker/check', [ToolsController::class, 'checkSerp']);
$router->post('/serp-checker/track', [ToolsController::class, 'trackKeyword']);
$router->get('/ai-content-assistant', [ToolsController::class, 'contentAssistant']);
$router->post('/ai-content-assistant/generate', [ToolsController::class, 'generateContent']);
$router->get('/ai-website-growth-consultant', [ToolsController::class, 'growthConsultant']);
$router->get('/instant-website-quote-calculator', [ToolsController::class, 'quoteCalculator']);
$router->get('/security-score-badge-generator', [ToolsController::class, 'securityBadge']);
$router->get('/client-portal-preview', [ToolsController::class, 'clientPortalPreview']);
$router->get('/ppc-roi-calculator', [ToolsController::class, 'ppcRoiCalculator']);
$router->get('/before-after-speed-simulator', [ToolsController::class, 'speedSimulator']);
$router->get('/ai-automation-finder', [ToolsController::class, 'automationFinder']);
$router->get('/support', [SupportController::class, 'index']);
$router->post('/support/tickets', [SupportController::class, 'store']);
$router->get('/ads.txt', [PageController::class, 'adsTxt']);
$router->post('/admin/ads-settings', [AdminController::class, 'updateAdsSettings']);
$router->post('/admin/search-console-settings', [AdminController::class, 'updateSearchConsoleSettings']);
$router->post('/admin/ai-settings', [AdminController::class, 'updateAiSettings']);
$router->post('/admin/work-log', [AdminController::class, 'saveWorkLog']);
$router->post('/admin/work-log/delete', [AdminController::class, 'deleteWorkLog']);
$router->post('/admin/clients', [AdminController::class, 'saveClient']);
$router->post('/admin/clients/state', [AdminController::class, 'clientState']);
$router->post('/admin/content-item/save', [AdminController::class, 'saveContentItem']);
$router->post('/admin/content-item/delete', [AdminController::class, 'deleteContentItem']);
$router->post('/admin/content-item/move', [AdminController::class, 'moveContentItem']);
$router->post('/admin/seo-settings', [AdminController::class, 'updateSeoSettings']);
$router->post('/admin/backup/download', [AdminController::class, 'downloadBackup']);
$router->get('/privacy-policy', [PageController::class, 'legal']);
$router->get('/cookie-policy', [PageController::class, 'legal']);
$router->get('/terms-and-conditions', [PageController::class, 'legal']);
$router->get('/search', [PageController::class, 'search']);
$router->get('/forum', [ForumController::class, 'index']);
$router->get('/forum/{slug}', [ForumController::class, 'show']);
$router->post('/forum/{slug}/posts', [ForumController::class, 'storePost']);
$router->get('/blog', [BlogController::class, 'index']);
$router->get('/blog/{slug}', [BlogController::class, 'show']);
$router->get('/admin', [AdminController::class, 'login']);
$router->post('/admin/login', [AdminController::class, 'authenticate']);
$router->get('/admin/dashboard', [AdminController::class, 'dashboard']);
$router->get('/admin/modules/{slug}', [AdminController::class, 'module']);
$router->post('/admin/modules/{slug}/actions', [AdminController::class, 'saveModuleDraft']);
$router->post('/admin/media/upload', [AdminController::class, 'uploadMedia']);
$router->post('/admin/forum-members/verify', [AdminController::class, 'verifyForumMember']);
$router->post('/admin/content/{section}', [AdminController::class, 'updateSiteContent']);
$router->post('/admin/backlink-plans', [AdminController::class, 'saveBacklinkPlan']);
$router->post('/admin/backlink-plans/state', [AdminController::class, 'deleteBacklinkPlan']);
$router->post('/admin/care-plans', [AdminController::class, 'saveCarePlan']);
$router->post('/admin/care-plans/state', [AdminController::class, 'carePlanState']);
$router->post('/admin/coupons', [AdminController::class, 'saveCoupon']);
$router->post('/admin/coupons/state', [AdminController::class, 'couponState']);
$router->post('/admin/test-member', [AdminController::class, 'createTestMember']);
$router->post('/admin/members/save', [AdminController::class, 'saveMember']);
$router->post('/admin/members/delete', [AdminController::class, 'deleteMember']);
$router->post('/admin/newsletter-offer', [AdminController::class, 'updateNewsletterOffer']);
$router->post('/admin/mail-settings', [AdminController::class, 'updateMailSettings']);
$router->post('/admin/mail-settings/test', [AdminController::class, 'testMailSettings']);
$router->post('/admin/paypal-settings', [AdminController::class, 'updatePayPalSettings']);
$router->get('/admin/cms/fonts', [AdminCmsController::class, 'fontOptions']);
$router->post('/admin/cms/add-missing-tables', [AdminCmsController::class, 'addMissingTables']);
$router->post('/admin/cms/theme-assets', [AdminCmsController::class, 'uploadThemeAsset']);
$router->post('/admin/cms/typography', [AdminCmsController::class, 'saveTypography']);
$router->post('/admin/cms/custom-code', [AdminCmsController::class, 'saveCustomCodeAsset']);
$router->post('/admin/cms/script-injections', [AdminCmsController::class, 'saveScriptInjection']);
$router->post('/admin/cms/products', [AdminCmsController::class, 'saveProduct']);
$router->post('/admin/cms/product-assets', [AdminCmsController::class, 'uploadProductAsset']);
$router->post('/admin/membership/plans', [AdminCommerceController::class, 'saveMembershipPlan']);
$router->post('/admin/membership/plans/toggle', [AdminCommerceController::class, 'toggleMembershipPlan']);
$router->post('/admin/membership/plans/delete', [AdminCommerceController::class, 'deleteMembershipPlan']);
$router->post('/admin/logout', [AdminController::class, 'logout']);

// Catch-all for Ireland location-SEO landing pages (e.g. /web-design-dublin,
// /seo-ireland). Registered LAST so every explicit route above wins first;
// LocationController::landing() renders a 404 for any non-location slug.
$router->get('/{slug}', [LocationController::class, 'landing']);
